### ISSUE TITLE
New Link under User Menu

### ISSUE THREAD

**Issue by ardyjr** [sharpchi/moodle-local_accessibilitytool#6] opened 2020-03-30 11:49 UTC
Hello, I've been experimenting with the tool and attempted to replicate it by just copying the essential files. However Moodle didn't take kindly to it so I had removed the plugin copy but there is now a dead link under the User Menu.

![error](https://user-images.githubusercontent.com/62884710/77909212-dd2a2e00-7284-11ea-9077-6a644b151ea6.png)

Edit: The error has also stopped the features from the original tool from working.

**Comment by sharpchi** [comment] 2020-03-30 12:29
This isn't the issue you raised with me in the messages on moodle.org.
You do have to be careful about the names of files etc when you decide to make a duplicate of a plugin.
To clear your error, even though you've removed the folder of your duplicate, you should uninstall the plugin: /admin/localplugins.php
To remove the menu item, go to: /admin/settings.php?section=themesettings and edit the customusermenuitems
You may need to purge the caches when you've done that.

**Closed as completed by sharpchi** 2020-03-30 12:29 UTC

**Comment by ardyjr** [comment] 2020-03-30 12:48
My apologies for the poor explanation. Thank you for the solutions

**Comment by ardyjr** [comment] 2020-03-30 12:54
I've checked the settings.php file under the Admin folder but I cannot seem to find the line to edit, am I looking in the wrong file?
